import {
  Loader2,
  Mail,
  Lock,
  User,
  Github,
  ChevronLeft,
  ChevronRight,
  Sun,
  Moon,
  Laptop,
  Menu,
  X,
  Check,
  Plus,
  Trash,
  Edit,
  Settings,
  LogOut,
} from "lucide-react";
import { Google } from "./ui/icons/google";

export const Icons = {
  spinner: Loader2,
  mail: Mail,
  lock: Lock,
  user: User,
  gitHub: Github,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  menu: Menu,
  close: X,
  check: Check,
  add: Plus,
  trash: Trash,
  edit: Edit,
  settings: Settings,
  logout: LogOut,
  google: Google,
} as const; 